package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDO;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Feb 26 10:38:55 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Feb 26 10:38:55 CST 2021
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Feb 26 10:38:55 CST 2021
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Feb 26 10:38:55 CST 2021
     */
    ItemStockDO selectByPrimaryKey(Integer id);
    //以下方法是自己根据业务逻辑加的，不是mybatis工具自动生成的
    ItemStockDO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Feb 26 10:38:55 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Feb 26 10:38:55 CST 2021
     */
    int updateByPrimaryKey(ItemStockDO record);
    /*
     *  扣减库存---->通过简单的update的语句实现
     *  innodb默认加行锁
     *  返回值是影响的行数
     *  正常扣减，返回值是1；否则返回值是0
     * */
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}